apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2fauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2fauth
  template:
    metadata:
      labels:
        app: 2fauth
    spec:
      containers:
        - name: 2fauth
          image: 2fauth/2fauth:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "2FAuth"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: DB_CONNECTION
              value: "sqlite"
          volumeMounts:
            - name: 2fauth-data
              mountPath: /2fauth
      volumes:
        - name: 2fauth-data
          persistentVolumeClaim:
            claimName: 2fauth-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: 2fauth
spec:
  type: ClusterIP
  selector:
    app: 2fauth
  ports:
    - port: 80
      targetPort: 8000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2fauth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
